import React, { useState } from 'react';
import { Database, BarChart2, GitBranch, Zap, ChevronDown, Star, ArrowRight, Table, Brain, Share2 } from 'lucide-react';

const FEATURES = [
  {
    icon: <Database size={22} color="#6b4cff" />,
    title: 'Natural Language → SQL',
    desc: 'Just ask a question in plain English. AgentDB converts it to SQL, runs it, and returns results instantly. No SQL knowledge needed.'
  },
  {
    icon: <BarChart2 size={22} color="#00C49F" />,
    title: 'Interactive Charts',
    desc: 'Bar, line, pie, and scatter charts rendered automatically from your data. Pin them to a dashboard and compare side by side.'
  },
  {
    icon: <GitBranch size={22} color="#FFBB28" />,
    title: 'ER & Flow Diagrams',
    desc: 'Visualize your database schema as an ER diagram or map your business processes as a flowchart — all from a single prompt.'
  },
  {
    icon: <Brain size={22} color="#FF8042" />,
    title: 'AI Insights',
    desc: 'Every query comes with bullet-point analysis generated by Gemini 2.5 Flash. Understand your data, not just the numbers.'
  },
  {
    icon: <Table size={22} color="#6b4cff" />,
    title: 'Multi-Database Support',
    desc: 'Upload and switch between multiple SQLite databases. Attach secondary DBs and query across them simultaneously.'
  },
  {
    icon: <Share2 size={22} color="#00C49F" />,
    title: 'Shareable Dashboards',
    desc: 'Pin charts and share your dashboard with a single link. Anyone with the link can view your insights — no login required.'
  },
];

const STEPS = [
  { num: '01', title: 'Connect your database', desc: 'Upload a SQLite, CSV, or JSON file. AgentDB parses the schema automatically.' },
  { num: '02', title: 'Ask in plain English', desc: 'Type any question about your data — queries, charts, diagrams, or insights.' },
  { num: '03', title: 'Get instant answers', desc: 'See results as tables, charts, ER diagrams, and AI-generated insights in seconds.' },
];

const TESTIMONIALS = [
  { quote: 'AgentDB replaced hours of manual SQL work. I just ask and get charts instantly.', name: 'Data Analyst', company: 'E-commerce startup' },
  { quote: 'The ER diagram feature alone saved us days of documentation work.', name: 'Backend Engineer', company: 'SaaS company' },
  { quote: 'Non-technical teammates can now explore our database without any help.', name: 'Product Manager', company: 'Tech company' },
];

const FAQS = [
  { q: 'What databases does AgentDB support?', a: 'AgentDB supports SQLite (.db, .sqlite), CSV, TSV, and JSON files. Upload any of these and start querying immediately.' },
  { q: 'Do I need to know SQL?', a: 'No. AgentDB converts your plain English questions into SQL automatically using Gemini 2.5 Flash.' },
  { q: 'Is my data safe?', a: 'Your database files are stored locally and processed on your own server. Nothing is sent to third parties except the schema and query context to the Gemini API.' },
  { q: 'Can I share my charts?', a: 'Yes. Pin any chart to the dashboard and click Share to get a public link anyone can view.' },
  { q: 'What chart types are supported?', a: 'Bar, line, pie, and scatter charts via Recharts. ER diagrams and flowcharts via Mermaid.js.' },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ borderBottom: '1px solid #2a2d35' }}>
      <button onClick={() => setOpen(o => !o)} style={{ width: '100%', background: 'none', border: 'none', padding: '18px 0', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer', textAlign: 'left', gap: 16 }}>
        <span style={{ color: '#fff', fontSize: '0.95rem', fontWeight: 500 }}>{q}</span>
        <ChevronDown size={16} color="#9ea4b0" style={{ flexShrink: 0, transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }} />
      </button>
      {open && <p style={{ color: '#9ea4b0', fontSize: '0.88rem', lineHeight: 1.7, paddingBottom: 18, margin: 0 }}>{a}</p>}
    </div>
  );
}

export default function LandingPage({ onLaunch }) {
  return (
    <div style={{ background: '#0a0b0f', color: '#fff', fontFamily: "-apple-system, BlinkMacSystemFont, 'Inter', sans-serif", overflowX: 'hidden' }}>

      {/* Nav */}
      <nav style={{ position: 'sticky', top: 0, zIndex: 50, background: 'rgba(10,11,15,0.85)', backdropFilter: 'blur(20px)', borderBottom: '1px solid #1a1d24', padding: '0 5vw', display: 'flex', alignItems: 'center', height: 60, gap: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, flex: 1 }}>
          <div style={{ width: 28, height: 28, borderRadius: 8, background: 'linear-gradient(135deg,#6b4cff,#4f46e5)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Database size={14} color="#fff" />
          </div>
          <span style={{ fontWeight: 700, fontSize: '1rem', letterSpacing: '-0.02em' }}>AgentDB</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: '0.75rem', color: '#9ea4b0', background: '#1a1d24', border: '1px solid #2a2d35', borderRadius: 20, padding: '3px 10px' }}>Powered by Gemini 2.5 Flash</span>
          <button onClick={onLaunch} style={{ background: '#6b4cff', color: '#fff', border: 'none', borderRadius: 8, padding: '8px 18px', fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer' }}>
            Launch App
          </button>
        </div>
      </nav>

      {/* Hero */}
      <section style={{ padding: '100px 5vw 80px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', top: '10%', left: '50%', transform: 'translateX(-50%)', width: 600, height: 600, background: 'radial-gradient(circle, rgba(107,76,255,0.15) 0%, transparent 70%)', pointerEvents: 'none' }} />
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: '#1a1d24', border: '1px solid #2a2d35', borderRadius: 20, padding: '5px 14px', fontSize: '0.78rem', color: '#9ea4b0', marginBottom: 28 }}>
          <Zap size={12} color="#6b4cff" /> AI-powered database intelligence
        </div>
        <h1 style={{ fontSize: 'clamp(2.2rem, 5vw, 4rem)', fontWeight: 800, lineHeight: 1.1, letterSpacing: '-0.03em', marginBottom: 24, maxWidth: 800, margin: '0 auto 24px' }}>
          Talk to your database<br />
          <span style={{ background: 'linear-gradient(135deg,#6b4cff,#00C49F)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>in plain English</span>
        </h1>
        <p style={{ color: '#9ea4b0', fontSize: 'clamp(1rem, 2vw, 1.15rem)', lineHeight: 1.7, maxWidth: 560, margin: '0 auto 40px' }}>
          Ask questions, get SQL queries executed, charts rendered, and AI insights — all in one response. No SQL knowledge required.
        </p>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12, flexWrap: 'wrap' }}>
          <button onClick={onLaunch} style={{ background: '#6b4cff', color: '#fff', border: 'none', borderRadius: 10, padding: '14px 32px', fontSize: '1rem', fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8 }}>
            Start for free <ArrowRight size={16} />
          </button>
          <span style={{ color: '#555', fontSize: '0.82rem' }}>No credit card required</span>
        </div>

        {/* Mock UI preview */}
        <div style={{ marginTop: 64, maxWidth: 860, margin: '64px auto 0', background: '#1a1d24', border: '1px solid #2a2d35', borderRadius: 16, overflow: 'hidden', boxShadow: '0 40px 80px rgba(0,0,0,0.5)' }}>
          <div style={{ background: '#141620', padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 6, borderBottom: '1px solid #2a2d35' }}>
            <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#ff5f57' }} />
            <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#febc2e' }} />
            <div style={{ width: 10, height: 10, borderRadius: '50%', background: '#28c840' }} />
            <span style={{ marginLeft: 8, fontSize: '0.75rem', color: '#555' }}>AgentDB — Intelligent Database Agent</span>
          </div>
          <div style={{ padding: '24px', textAlign: 'left' }}>
            <div style={{ display: 'flex', gap: 10, marginBottom: 16 }}>
              <div style={{ width: 32, height: 32, borderRadius: '50%', background: 'linear-gradient(135deg,#4f46e5,#7c3aed)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <Database size={13} color="#fff" />
              </div>
              <div style={{ background: '#0f1117', borderRadius: '0 12px 12px 12px', padding: '10px 14px', fontSize: '0.85rem', color: '#e0e0e0', lineHeight: 1.6 }}>
                Hello! I'm AgentDB. Ask me anything about your database — queries, charts, diagrams, or insights.
              </div>
            </div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 16 }}>
              <div style={{ background: '#6b4cff', borderRadius: '12px 12px 0 12px', padding: '10px 14px', fontSize: '0.85rem', color: '#fff' }}>
                Show a bar chart of sales by product category
              </div>
            </div>
            <div style={{ display: 'flex', gap: 10 }}>
              <div style={{ width: 32, height: 32, borderRadius: '50%', background: 'linear-gradient(135deg,#4f46e5,#7c3aed)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <Database size={13} color="#fff" />
              </div>
              <div style={{ background: '#0f1117', borderRadius: '0 12px 12px 12px', padding: '10px 14px', fontSize: '0.85rem', color: '#e0e0e0', flex: 1 }}>
                <p style={{ margin: '0 0 10px' }}>Here's the bar chart of sales by product category:</p>
                <div style={{ background: '#141620', borderRadius: 8, padding: '12px', display: 'flex', alignItems: 'flex-end', gap: 8, height: 80 }}>
                  {[65, 85, 45, 90, 55, 70].map((h, i) => (
                    <div key={i} style={{ flex: 1, height: `${h}%`, background: ['#6b4cff','#00C49F','#FFBB28','#FF8042','#8884d8','#6b4cff'][i], borderRadius: '3px 3px 0 0', opacity: 0.85 }} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Logos / trust */}
      <section style={{ padding: '20px 5vw 60px', textAlign: 'center' }}>
        <p style={{ color: '#555', fontSize: '0.78rem', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 20 }}>Built with</p>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 32, flexWrap: 'wrap' }}>
          {['FastAPI', 'LangGraph', 'Gemini 2.5 Flash', 'React', 'Recharts', 'Mermaid.js'].map(t => (
            <span key={t} style={{ color: '#555', fontSize: '0.85rem', fontWeight: 500 }}>{t}</span>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section style={{ padding: '80px 5vw', background: '#0d0e14' }}>
        <div style={{ maxWidth: 900, margin: '0 auto' }}>
          <p style={{ color: '#6b4cff', fontSize: '0.78rem', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 12, textAlign: 'center' }}>How it works</p>
          <h2 style={{ fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, textAlign: 'center', marginBottom: 56, letterSpacing: '-0.02em' }}>From question to insight in seconds</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 32 }}>
            {STEPS.map((s, i) => (
              <div key={i} style={{ position: 'relative' }}>
                <div style={{ fontSize: '2.5rem', fontWeight: 800, color: '#1a1d24', marginBottom: 12, lineHeight: 1 }}>{s.num}</div>
                <h3 style={{ fontSize: '1rem', fontWeight: 600, marginBottom: 8 }}>{s.title}</h3>
                <p style={{ color: '#9ea4b0', fontSize: '0.88rem', lineHeight: 1.7, margin: 0 }}>{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section style={{ padding: '80px 5vw' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <p style={{ color: '#6b4cff', fontSize: '0.78rem', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 12, textAlign: 'center' }}>Features</p>
          <h2 style={{ fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, textAlign: 'center', marginBottom: 56, letterSpacing: '-0.02em' }}>Everything you need to understand your data</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 24 }}>
            {FEATURES.map((f, i) => (
              <div key={i} style={{ background: '#1a1d24', border: '1px solid #2a2d35', borderRadius: 14, padding: '24px', transition: 'border-color 0.2s', cursor: 'default' }}
                onMouseEnter={e => e.currentTarget.style.borderColor = '#6b4cff'}
                onMouseLeave={e => e.currentTarget.style.borderColor = '#2a2d35'}>
                <div style={{ marginBottom: 14 }}>{f.icon}</div>
                <h3 style={{ fontSize: '0.95rem', fontWeight: 600, marginBottom: 8 }}>{f.title}</h3>
                <p style={{ color: '#9ea4b0', fontSize: '0.85rem', lineHeight: 1.7, margin: 0 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section style={{ padding: '80px 5vw', background: '#0d0e14' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto' }}>
          <h2 style={{ fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, textAlign: 'center', marginBottom: 56, letterSpacing: '-0.02em' }}>Loved by data teams</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 24 }}>
            {TESTIMONIALS.map((t, i) => (
              <div key={i} style={{ background: '#1a1d24', border: '1px solid #2a2d35', borderRadius: 14, padding: '24px' }}>
                <div style={{ display: 'flex', gap: 2, marginBottom: 14 }}>
                  {[...Array(5)].map((_, j) => <Star key={j} size={13} fill="#FFBB28" color="#FFBB28" />)}
                </div>
                <p style={{ color: '#e0e0e0', fontSize: '0.9rem', lineHeight: 1.7, marginBottom: 16 }}>"{t.quote}"</p>
                <div>
                  <div style={{ fontSize: '0.82rem', fontWeight: 600 }}>{t.name}</div>
                  <div style={{ fontSize: '0.78rem', color: '#9ea4b0' }}>{t.company}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section style={{ padding: '80px 5vw' }}>
        <div style={{ maxWidth: 680, margin: '0 auto' }}>
          <h2 style={{ fontSize: 'clamp(1.6rem, 3vw, 2.4rem)', fontWeight: 700, textAlign: 'center', marginBottom: 48, letterSpacing: '-0.02em' }}>Frequently asked questions</h2>
          {FAQS.map((f, i) => <FAQItem key={i} {...f} />)}
        </div>
      </section>

      {/* CTA */}
      <section style={{ padding: '80px 5vw', textAlign: 'center', background: '#0d0e14' }}>
        <h2 style={{ fontSize: 'clamp(1.8rem, 3vw, 2.8rem)', fontWeight: 800, marginBottom: 16, letterSpacing: '-0.03em' }}>
          When it comes to your data,<br />all you need is AgentDB
        </h2>
        <p style={{ color: '#9ea4b0', marginBottom: 36, fontSize: '1rem' }}>Start querying your database in plain English today.</p>
        <button onClick={onLaunch} style={{ background: '#6b4cff', color: '#fff', border: 'none', borderRadius: 10, padding: '14px 36px', fontSize: '1rem', fontWeight: 700, cursor: 'pointer', display: 'inline-flex', alignItems: 'center', gap: 8 }}>
          Launch AgentDB <ArrowRight size={16} />
        </button>
        <p style={{ color: '#555', fontSize: '0.8rem', marginTop: 12 }}>Free · No credit card required</p>
      </section>

      {/* Footer */}
      <footer style={{ borderTop: '1px solid #1a1d24', padding: '32px 5vw', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 24, height: 24, borderRadius: 6, background: 'linear-gradient(135deg,#6b4cff,#4f46e5)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Database size={12} color="#fff" />
          </div>
          <span style={{ fontWeight: 700, fontSize: '0.9rem' }}>AgentDB</span>
        </div>
        <div style={{ display: 'flex', gap: 24 }}>
          <a href="https://github.com/prasannaraj12/AgentDB" target="_blank" rel="noreferrer" style={{ color: '#9ea4b0', fontSize: '0.82rem', textDecoration: 'none' }}>GitHub</a>
          <span style={{ color: '#555', fontSize: '0.82rem' }}>Built for iTech AI Innovation Hackathon 2026</span>
        </div>
        <span style={{ color: '#555', fontSize: '0.78rem' }}>© 2026 AgentDB · MIT License</span>
      </footer>
    </div>
  );
}
